name: Build and Push Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "23 13 3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push ubuntu based container image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/l4r5/esodb-exporter:latest
        platforms: linux/amd64
        dockerfile_path: Dockerfile

    - name: Build and push alpine based container image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/l4r5/esodb-exporter:alpine-latest
        platforms: linux/amd64
        dockerfile_path: Dockerfile.alpine

